// Textes de référence de la calibration (spec signaux §8)
export const AI_EN = `In today's rapidly evolving digital landscape, artificial intelligence plays a pivotal role in shaping how organizations operate. Furthermore, it offers a comprehensive framework for improving efficiency across many sectors. This transformation is not just a technological shift, it is a profound cultural change. Moreover, companies must navigate an intricate web of challenges to remain competitive.
Data privacy remains a crucial concern for organizations adopting artificial intelligence today. Additionally, robust governance frameworks help ensure responsible and ethical deployment. These measures foster trust, transparency, and accountability among users. Consequently, leaders must leverage these frameworks to build lasting confidence.
Education also stands to benefit greatly from artificial intelligence in many ways. Furthermore, personalized learning tools adapt to the unique needs of each student. This approach underscores the importance of flexible and inclusive teaching methods. Moreover, teachers can focus on mentoring, creativity, and critical thinking skills.
Ultimately, the future of artificial intelligence depends on thoughtful and collaborative leadership. Its responsible adoption serves as a testament to human ingenuity and vision. Organizations that embrace this change will thrive in a complex world. Overall, artificial intelligence represents a pivotal opportunity for meaningful progress.`;

export const HUMAN_EN = `I tried the new bakery on Fifth Street yesterday. Huge mistake? Not at all. The croissants were flaky in a way I haven't seen since that trip to Lyon, years ago, when my sister dragged me out of bed at six to queue behind a dozen locals who clearly knew something we didn't.
Prices are steep, though. Four dollars for a croissant. My dad would have laughed.
The owner, a tall guy with flour on his glasses, told me he gets the butter from a farm upstate and that he nearly quit last winter because the oven kept breaking down and the repairman never called back. He seemed tired but proud. I bought two more for the road.
Will I go back? Probably on Sunday, if the rain holds off and my knee stops complaining.`;

export const AI_FR = `Dans un monde en constante évolution, l'intelligence artificielle joue un rôle crucial dans la transformation des entreprises. En outre, elle offre des outils incontournables pour améliorer la productivité des équipes. Ce n'est pas seulement une avancée technique, c'est une véritable révolution culturelle. Par ailleurs, les organisations doivent adopter une approche méticuleuse et réfléchie.
La protection des données demeure un enjeu primordial pour les organisations modernes. De plus, une gouvernance robuste permet de garantir une utilisation éthique et responsable. Ces mesures favorisent la confiance, la transparence et la responsabilité des utilisateurs. Par conséquent, les dirigeants doivent s'appuyer sur ces principes pour bâtir l'avenir.
L'éducation constitue également un domaine essentiel pour l'intelligence artificielle aujourd'hui. En effet, les outils personnalisés s'adaptent aux besoins spécifiques de chaque élève. Cette évolution souligne l'importance de méthodes pédagogiques flexibles et inclusives. Ainsi, les enseignants peuvent se concentrer sur la créativité, l'écoute et l'esprit critique.
En définitive, l'avenir de l'intelligence artificielle repose sur une vision collective et ambitieuse. Son adoption responsable témoigne de l'ingéniosité humaine et de notre capacité d'adaptation. Les organisations qui embrassent ce changement réussiront dans un monde complexe. En somme, l'intelligence artificielle représente une opportunité incontestablement majeure pour notre société.`;

export const HUMAN_FR = `Hier soir, panne de courant dans tout le quartier. On a sorti les bougies, évidemment, et mon fils a décrété que c'était la meilleure soirée de l'année.
Bon. Le congélateur, lui, n'était pas d'accord.
J'ai passé une bonne heure à vider les bacs dans la baignoire remplie de glaçons que la voisine du troisième nous avait gentiment apportés, en râlant contre le fournisseur d'électricité, contre moi-même qui n'avais jamais acheté de groupe électrogène malgré les promesses répétées depuis trois hivers, et contre le chat qui se faufilait partout.
Le courant est revenu vers minuit. Trop tard pour les glaces. Tant pis, on les a mangées.`;
